[tool.poetry]
name = "ecommerce-app"
version = "1.0.0"
description = "E-commerce Django React Application"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
