# Generated by Django 4.1.7 on 2025-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
    ]
