# Generated by Django 5.2.3 on 2025-07-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_isrefunded_refundrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
