# Generated by Django 4.2.23 on 2025-07-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_order_isrefunded_refundrequest"),
        ("api", "0009_order_coupon"),
        ("api", "0009_product_total_sold"),
    ]

    operations = []
