# Generated by Django 5.2.3 on 2025-07-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_isrefunded_refundrequest'),
        ('api', '0010_message'),
    ]

    operations = [
    ]
