# Generated by Django 5.2.3 on 2025-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250706_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='is_approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
