# Generated by Django 5.2.3 on 2025-07-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_total_sold'),
        ('api', '0012_alter_refundrequest_is_approved_delete_message'),
    ]

    operations = [
    ]
