# Generated by Django 5.2.3 on 2025-07-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_refundrequest_is_approved'),
        ('api', '0013_merge_20250706_1539'),
    ]

    operations = [
    ]
