# Generated by Django 5.2.3 on 2025-07-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_refundrequest_is_approved'),
        ('api', '0014_merge_20250706_2036'),
    ]

    operations = [
    ]
