# Generated by Django 5.2.3 on 2025-07-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatreadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatReadStatus',
        ),
    ]
